sudo: require

language: bash

branches:
    only:
        - master

notifications:
    email: false

env:
    global:
        # Github Token for pushing the built docs (GH_TOKEN)

before_install:
    - sudo apt-get -q update
    - sudo apt-get install -y texlive-full

script:
    - make

deploy:
    # Push the PDF to a branch
    - provider: script
      script: ci/deploy-pdf.sh
      skip_cleanup: true
      on:
          branch: master
