# The name of the main .tex file to build.
# Other files can be included into this one.
SOURCES = cover-letter.tex curriculum-vitae.tex
TARGETS = $(patsubst %.tex, %.pdf, $(SOURCES))
OUTPUT = leonardo_uieda_coverletter_and_cv.pdf

LATEX_FLAGS = -halt-on-error
LATEX = pdflatex

### Set commands for opening the generated PDF
UNAME := $(shell uname)
ifeq ($(UNAME), Linux)
PDFVIEWER = xdg-open
endif
ifeq ($(UNAME), Darwin)
PDFVIEWER = open
endif

# TARGETS
###############################################################################

all: $(OUTPUT)

# Open the PDF
show: $(OUTPUT)
	@ # Redirect stdout and stderr to /dev/null for silent execution
	@ (${PDFVIEWER} $(OUTPUT) > /dev/null 2>&1 & )

$(OUTPUT): $(TARGETS)
	pdfunite $^ $@

%.pdf: %.tex
	$(LATEX) $(LATEX_FLAGS) $<
	$(LATEX) $(LATEX_FLAGS) $< 1>/dev/null

### Clean
# This target cleans the temporary files generated by the tex programs
clean:
	rm -rf *.aux *.log *.bbl *.blg *.out *.toc
	rm -rf $(TARGETS) $(OUTPUT)
	rm -rf images/*-eps-converted-to.pdf
