# The name of the main .tex file to build.
# Other files can be included into this one.
SOURCES = $(wildcard *.tex)
TARGETS = $(patsubst %.tex, %.pdf, $(SOURCES))

LATEX_FLAGS = -halt-on-error
LATEX = pdflatex


# TARGETS
###############################################################################

all: $(TARGETS)

%.pdf: %.tex
	$(LATEX) $(LATEX_FLAGS) $<
	$(LATEX) $(LATEX_FLAGS) $< 1>/dev/null

### Clean
# This target cleans the temporary files generated by the tex programs
clean:
	rm -rf *.aux *.log *.bbl *.blg *.out *.toc
	rm -rf $(TARGETS)
	rm -rf images/*-eps-converted-to.pdf
