# The name of the main .tex file to build.
# Other files can be included into this one.
SOURCES = $(wildcard *.tex)
TARGETS = $(patsubst %.tex, %.pdf, $(SOURCES))

LATEX_FLAGS = -halt-on-error
LATEX = pdflatex

### Set commands for opening the generated PDF
UNAME := $(shell uname)
ifeq ($(UNAME), Linux)
PDFVIEWER = xdg-open
endif
ifeq ($(UNAME), Darwin)
PDFVIEWER = open
endif


# TARGETS
###############################################################################

all: $(TARGETS)

%.pdf: %.tex
	$(LATEX) $(LATEX_FLAGS) $<
	$(LATEX) $(LATEX_FLAGS) $< 1>/dev/null

show: all
	@ # Redirect stdout and stderr to /dev/null for silent execution
	@ (${PDFVIEWER} $(TARGETS) > /dev/null 2>&1 & )

### Clean
# This target cleans the temporary files generated by the tex programs
clean:
	rm -rf *.aux *.log *.bbl *.blg *.out *.toc
	rm -rf $(TARGETS)
	rm -rf images/*-eps-converted-to.pdf
